#!/bin/sh -e

value=$(snapctl get --view :proxy-observe -d)
echo "$value" > "$SNAP_COMMON"/view-changed-proxy-observe

# for instance, you can use this hook to watch for configuration changes
# and restart services if needed
